// Actions
export const MARRANITO_GET_ACCOUNT = 'MARRANITO_GET_ACCOUNT';
export const MARRANITO_INIT_CONTRACT = 'MARRANITO_INIT_CONTRACT';
export const MARRANITO_SEND_FUNDS = 'MARRANITO_SEND_FUNDS';

// Mutations
export const MARRANITO_SET_ACCOUNT = 'MARRANITO_SET_ACCOUNT';
export const MARRANITO_SET_BALANCE = 'MARRANITO_SET_BALANCE';
export const MARRANITO_SET_MARRANITO_BALANCE = 'MARRANITO_SET_MARRANITO_BALANCE';
export const MARRANITO_SET_INSTANCE = 'MARRANITO_SET_INSTANCE';
export const MARRANITO_SET_IS_OWNER = 'MARRANITO_SET_IS_OWNER';

// Getters
